### ISSUE TITLE
Hosting on Heroku

### ISSUE THREAD

**Issue by garimasingh128** [garimasingh128/Draw#2]
- Host on Heroku with a custom domain name

**Comment by Siddhant-K-code** [comment]
Can I do this?

**Comment by KerinPithawala** [comment]
Can you assign this issue to me?

**Comment by Siddhant-K-code** [comment]
What custom domain name you want?

i Deployed this for now: https://draw-with-garima.herokuapp.com/

**Comment by garimasingh128** [comment]
The domain looks fine. Will review the pr.

**Comment by Siddhant-K-code** [comment]
reopened?
